version: "3"

services:
  postgres:
    container_name: award_app_postgres
    image: postgres:alpine3.16
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
